# Generated by Django 2.1.1 on 2018-10-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmybicycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='sloc',
            field=models.CharField(max_length=100),
        ),
    ]
