# Generated by Django 2.1.1 on 2018-10-15 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmybicycle', '0002_auto_20181014_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='bookmybicycle.Cycle'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sid_end',
            field=models.ForeignKey(db_column='sid_end', default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='sid_end', to='bookmybicycle.Stand'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sid_start',
            field=models.ForeignKey(db_column='sid_start', default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='sid_start', to='bookmybicycle.Stand'),
        ),
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
