# Generated by Django 2.1.1 on 2018-10-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmybicycle', '0003_auto_20181015_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='bookmybicycle.Stand'),
        ),
    ]
